### PR TITLE
Document Xamarin SDK

### PR DESCRIPTION
**Pull request by louischan-oursky**

### CODE REVIEW

**Review by carmenlau — COMMENTED** [review]
The PR looks good for me. Please feel free to merge it after updating the url scheme in the example.

I tried creating a new app and test the code, but there are some problems. I am not familiar with Xamarin, so that may be problems of my setup. May I have your help to have a quick check what is the problem? Just want to ensure the doc is good enough for beginners. 🙇🏻‍♀️

https://github.com/carmenlau/authgear-xamarin-test/commit/dc9f869320649ea2e2a5b98a021429673195aae8

In Android, I failed to build with following error
```
.../xamarin-demo/myapp/myapp.Android/MainActivity.cs(32,32): Error CS1729: 'AuthgearSdk' does not contain a constructor that takes 2 arguments (CS1729) (myapp.Android)
```
In iOS, I got run time exception when I click authenticate.
```
System.TypeLoadException has been thrown
Could not resolve type with token 01000080 from typeref (expected class 'Xamarin.Essentials.WebAuthenticatorOptions' in assembly 'Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')
```

**Comment by roxk** [comment]
Lemme take a look at carmen's test code.

**Comment by roxk** [comment]
Can reproduce for android project. There is also some doc steps that are missing I believe:
1. Each platform project needs to reference `Authgear.Xamarin` as well to pick up the _platform specific_ binary.

Checking the metadata reveals that the project is grabbing the authgear lib for `netstandard`, instead of `monoandroid`. Investigating.

**Comment by roxk** [comment]
It's a target version problem. Our lib targets monoandroid 12.0, whereas myapp.android targets 11.0, thus it refused to pick up the android specific binary, and picked `netstandard` binary instead. Glad we adopted platform-specific constructor, otherwise the code would compile and would crash at runtime as `netstandard` binary is never meant to be picked up. 

Updating the target framework of myapp.android in properties -> target framework to 12, cleaning and rebuild again (or just delete /obj) fixes the issue.

I suspect ios has similar problem, and the xamarin.essential version it's referencing isn't every correct😅 The log says 1.0.0.0 but we are referencing 1.7.2.

@louischan-oursky Seems like we need to mention target framework issue in the guide as well. Lemme create a PR.

**Comment by roxk** [comment]
Tested, manually adding authgear.xamarin to android project is **NOT** needed. Only adding to base project is fine. Only added instructions to update target framework in the instructions.

**Comment by roxk** [comment]
For iOS, the version of xamarin.essential is important as v1.6.x doesn't have web authenticator. As the default uses 1.6.x, we need to add instructions to make sure the version is at least 1.7.2.

**Comment by carmenlau** [comment]
Thanks @roxk!!
I just tried updated my setup, I can open the ASWebAuthenticationSession now. But after I authenticate and redirect back to the app, I got this error. Do I need some setup for that?

```
System.Exception: Error adding record: MissingEntitlement
  at Xamarin.Essentials.KeyChain.SetValueForKey (System.String value, System.String key, System.String service) [0x0009a] in D:\a\_work\1\s\Xamarin.Essentials\SecureStorage\SecureStorage.ios.tvos.watchos.macos.cs:126
  at Xamarin.Essentials.SecureStorage.SetAsync (System.String key, System.String value, Security.SecAccessible accessible) [0x00027] in D:\a\_work\1\s\Xamarin.Essentials\SecureStorage\SecureStorage.ios.tvos.watchos.macos.cs:24
  at Xamarin.Essentials.SecureStorage.PlatformSetAsync (System.String key, System.String data) [0x00000] in D:\a\_work\1\s\Xamarin.Essentials\SecureStorage\SecureStorage.ios.tvos.watchos.macos.cs:38
  at Xamarin.Essentials.SecureStorage.SetAsync (System.String key, System.String value) [0x00021] in D:\a\_work\1\s\Xamarin.Essentials\SecureStorage\SecureStorage.shared.cs:27
  at Authgear.Xamarin.Data.PersistentTokenStorage.SetRefreshToken (System.String aNamespace, System.String refreshToken) [0x0000b] in <8a60271c58334a73943b6cba50114694>:0
  at Authgear.Xamarin.AuthgearSdk.SaveToken (Authgear.Xamarin.Oauth.OidcTokenResponse tokenResponse, Authgear.Xamarin.SessionStateChangeReason reason) [0x000c7] in <8a60271c58334a73943b6cba50114694>:0
  at Authgear.Xamarin.AuthgearSdk.FinishAuthenticationAsync (System.String deepLink, System.String codeVerifier) [0x000a6] in <8a60271c58334a73943b6cba50114694>:0
  at Authgear.Xamarin.AuthgearSdk.AuthenticateAsync (Authgear.Xamarin.AuthenticateOptions options) [0x00181] in <8a60271c58334a73943b6cba50114694>:0
  at myapp.MainPage.Authenticate_Clicked (System.Object sender, System.EventArgs e) [0x00036] in /.../xamarin-demo/myapp/myapp/MainPage.xaml.cs:31
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/Foundation/NSAction.cs:178
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/UIKit/UIApplication.cs:75
  at myapp.iOS.Application.Main (System.String[] args) [0x00001] in /.../xamarin-demo/myapp/myapp.iOS/Main.cs:17
```

**Review by carmenlau — APPROVED** [review]

**Pull request merged**
