### PR TITLE
Document Deno Hooks

### PR DESCRIPTION
**Pull request by louischan-oursky**

### CODE REVIEW

**Review by fungc-io — APPROVED** [review]

**Review by carmenlau — COMMENTED** [review]
- Not sure if it is easy for the user to find this page if they don't know what deno is. Should we change the title to **Deno Hooks (JavaScript / TypeScript)**. Any idea?
- Please add new event `user.session.jwt.pre_create`

**Comment by fungc-io** [comment]
> Should we change the title to Deno Hooks (JavaScript / TypeScript)

Agree

**Comment by fungc-io** [comment]
@louischan-oursky sorry I just noticed it, the hook page path is `integrate/index` and `/integrate/index/event-list`, etc? how about changing it to `integrate/events-and-hooks`

**Comment by louischan-oursky** [comment]
1. Renamed Deno Hooks to "JavaScript / TypeScript Hooks" or "Hooks" for short
2. Fixed the URLs.
3. Added documentation for the new event `user.session.jwt.pre_create`

**Pull request merged**
